#ifndef SIP_SYSPACKET_H
#define SIP_SYSPACKET_H


#define PACKET_VERSION	20180102


#define SIP_MSG_NAME_DWORD

#ifdef SIP_MSG_NAME_DWORD
#define MsgNameType	uint32
#else
#define MsgNameType	std::string
#endif // SIP_MSG_NAME_DWORD


// Message Define
#ifdef SIP_MSG_NAME_DWORD

enum SYS_PACKETS
{
	M_SYS_EMPTY = 0xFFFFFFFF,
	M_WAIT = 101,
	M_CONNECT,

	M_UDP_KEEPALIVEPUBLIC = 150,

	M_REGISTER_PEER = 201,
	M_CS_UNREGISTER_PEER,
	M_REQ_CONNECT_PEER,
	M_CS_RES_CONNECT_PEER,
	M_SC_CONNECT_PEER,
	M_CS_CONNECT_PEER_OK,
	M_SC_DISCONNECT_PEER,

	M_CLIENTHELLO = 301,
	M_CERTIFICATE,
	M_KEYEXCHANGE,
	M_SERVERHELLO,
	M_HANDSHKFAIL,
	M_HANDSHKOK,
	M_CYCLEPING,

	M_SECURITYCLIENT_REFUSE = 403,
	M_SECURITYCLIENT_CANCONNECT,
	M_SECURITYCLIENT_GMCONNECT,

	M_ADMIN_EXEC_COMMAND_RESULT = 501,
	M_ADMIN_ADMIN_PONG,
	M_ADMIN_SID,
	M_ADMIN_SHARDID,
	M_SR,
	M_ADMIN_VIEW,
	M_ADMIN_ADMIN_EMAIL,
	M_ADMIN_GRAPH_UPDATE,
	M_ADMIN_INFO,
	M_ADMIN_GET_VIEW,
	M_ADMIN_STOPS,
	M_ADMIN_EXEC_COMMAND,
	M_ADMIN_ADMIN_PING,

	M_MODULE_15_TRANSPORT_GW_L5_ADDTP = 601,
	M_MODULE_15_TRANSPORT_GW_L5_MSG,
	M_MODULE_15_TRANSPORT_GW_L5_REMTP,

	M_LOGIN_SERVER_RPC = 701,
	M_CLIENT_DISCONNECT,
	M_ENTER_SHARD_ANSWER,
	M_LOGIN_SERVER_FORCESV,
	M_ENTER__SHARD,
	M_CLIENT_CONNECT_STATUS,
	M_ENTER_SHARD_REQUEST,
	M_KA,

	M_MODULE_GATEWAY_MOD_OP = 901,
	M_MODULE_GATEWAY_MOD_UPD,
	M_EXCEPT,
	M_DEBUG_MOD_PING,

	M_UNIFIED_NETWORK_UN_SIDENT = 1101,

	M_UNITIME_GUT = 1201,
	M_UNITIME_AUT,

	M_TRANSPORT_CLASS_CT_MSG = 1301,
	M_TRANSPORT_CLASS_CT_LRC,

	M_SERVICE_R_SH_ID = 1401,

	M_NET_DISPLAYER_LOG = 1501,

	M_NAMING_CLIENT_ACK_UNI = 1601,
	M_NAMING_CLIENT_RG,
	M_NAMING_CLIENT_QP,
	M_NAMING_CLIENT_RGB,
	M_NAMING_CLIENT_UNB,
	M_NAMING_CLIENT_RRG,
	M_NAMING_CLIENT_UNI,

	M_SS_UPDATE,
	M_SS_AUTH,

	M_NAT_CS_REQUESTNATHAVE = 1701,
	M_NAT_SC_REQUESTNATHAVE,
	M_NAT_CS_REQNATTYPE1,	
	M_NAT_CS_REQNATTYPE2 = 1705,		
	M_NAT_SC_REQNATTYPE,
	M_NAT_CS_REQCONETYPE,
	M_NAT_SC_REQCONETYPE,
	M_NAT_CS_COMPLETEDETECTION,

	M_UHP_CS_CLIENTREGISTER = 1801,		
	M_UHP_SC_CLIENTREGISTER,
	M_UHP_CS_UDPPORTEXCHANGE,				
	M_UHP_SC_UDPPORTEXCHANGE,
	M_UHP_CS_CONNECTPRIVATE,				
	M_UHP_SC_CONNECTPRIVATE,
	M_UHP_CS_CONNECTPUBLIC,					
	M_UHP_SC_CONNECTPUBLIC,
	M_UHP_CS_HOLEPUNCHINGEND = 1811,
	M_UHP_SC_TARGETEXIT,
	M_UHP_CS_HOLEPUNCHINGSUCCESS,

	M_P2P_CS_REGISTERTORELAY = 1901,
	M_P2P_SC_REGISTERTORELAY,

	M_ADDEDJIFEN = 2000,
};

#else

#define M_SYS_EMPTY							""
#define M_WAIT								"WAIT"
#define M_CONNECT							"CONNECT"

#define M_REGISTER_PEER						"REGISTER_PEER"				// M_CS_REGISTER_PEER : Peer등록요청([s:hostname])
																		// M_SC_REGISTER_PEER : Peer등록응답([b:bTcp=false][d:PeerID][s:Broker "IP:Port"][s:Relay "IP:Port"])
#define M_CS_UNREGISTER_PEER				"UNREGISTER_PEER"			// Peer삭제요청([d:요청자PeerID])
#define M_REQ_CONNECT_PEER					"REQUEST_CONNECT_PEER"		// M_CS_REQ_CONNECT_PEER : P2P접속요청송신([d:자기가족ID][d:상대가족ID][s:자기콤퓨터주소])
																		// M_SC_REQ_CONNECT_PEER : P2P접속요청수신([d:상대가족ID])
#define M_CS_RES_CONNECT_PEER				"RESPONSE_CONNECT_PEER"		// P2P접속요청응답송신([d:자기가족ID][d:상대가족ID][s:자기콤퓨터주소])
#define M_SC_CONNECT_PEER					"CONFIRM_CONNECT_PEER"		// P2P접속지령([d:상대가족ID][s:상대콤퓨터대역주소][s:상태콤퓨터국부주소][b:bSameLocal])
#define M_CS_CONNECT_PEER_OK				"CONNECT_PEER_OK"			// P2P접속성공통지([d:상대가족ID])
#define M_SC_DISCONNECT_PEER				"PEER_DISCONNECT"			// Peer탈퇴

#define M_CLIENTHELLO						"CLIENTHELLO"
#define M_CERTIFICATE						"CERTIFICATE"
#define M_KEYEXCHANGE						"KEYEXCHANGE"
#define M_SERVERHELLO						"SERVERHELLO"
#define M_HANDSHKFAIL						"HANDSHKFAIL"
#define M_HANDSHKOK							"HANDSHKOK"
#define M_CYCLEPING							"CYCLEPING"

#define M_SECURITYCLIENT_REFUSE				"REFUSE"
#define M_SECURITYCLIENT_CANCONNECT			"CANCONNECT"
#define M_SECURITYCLIENT_GMCONNECT			"GMCONNECT"

#define M_ADMIN_EXEC_COMMAND_RESULT			"EXEC_COMMAND_RESULT"
#define M_ADMIN_ADMIN_PONG					"ADMIN_PONG"
#define M_ADMIN_SID							"SID"
#define M_ADMIN_SHARDID						"SHARDID"
#define M_SR								"SR"
#define M_ADMIN_VIEW						"VIEW"
#define M_ADMIN_ADMIN_EMAIL					"ADMIN_EMAIL"
#define M_ADMIN_GRAPH_UPDATE				"GRAPH_UPDATE"
#define M_ADMIN_INFO						"INFO"
#define M_ADMIN_GET_VIEW					"GET_VIEW"
#define M_ADMIN_STOPS						"STOPS"
#define M_ADMIN_EXEC_COMMAND				"EXEC_COMMAND"
#define M_ADMIN_ADMIN_PING					"ADMIN_PING"

#define M_MODULE_15_TRANSPORT_GW_L5_ADDTP	"GW_L5_ADDTP"
#define M_MODULE_15_TRANSPORT_GW_L5_MSG		"GW_L5_MSG"
#define M_MODULE_15_TRANSPORT_GW_L5_REMTP	"GW_L5_REMTP"

#define M_LOGIN_SERVER_RPC					"RPC"
#define M_CLIENT_DISCONNECT					"DC"
#define M_ENTER_SHARD_ANSWER					"SCS"
#define M_LOGIN_SERVER_FORCESV				"FORCESV"
#define M_ENTER__SHARD					"SV"
#define M_CLIENT_CONNECT_STATUS					"CC"
#define M_ENTER_SHARD_REQUEST					"CS"
#define M_KA								"KA"

#define M_MODULE_GATEWAY_MOD_OP				"MOD_OP"
#define M_MODULE_GATEWAY_MOD_UPD			"MOD_UPD"
#define M_EXCEPT							"EXCEPT"
#define M_DEBUG_MOD_PING					"DEBUG_MOD_PING"

#define M_UNIFIED_NETWORK_UN_SIDENT			"UN_SIDENT"

#define M_UNITIME_GUT						"GUT"
#define M_UNITIME_AUT						"AUT"

#define M_TRANSPORT_CLASS_CT_MSG			"CT_MSG"
#define M_TRANSPORT_CLASS_CT_LRC			"CT_LRC"

#define M_SERVICE_R_SH_ID					"R_SH_ID"

#define M_NET_DISPLAYER_LOG					"LOG"

#define M_NAMING_CLIENT_ACK_UNI				"ACK_UNI"
#define M_NAMING_CLIENT_RG					"RG"
#define M_NAMING_CLIENT_QP					"QP"
#define M_NAMING_CLIENT_RGB					"RGB"
#define M_NAMING_CLIENT_UNB					"UNB"
#define M_NAMING_CLIENT_RRG					"RRG"
#define M_NAMING_CLIENT_UNI					"UNI"

#define M_SS_UPDATE							"UPDATE"
#define M_SS_AUTH							"AUTH"
#define M_NAT_CS_REQUESTNATHAVE				"NAT_CS_REQUESTNATHAVE"
#define M_NAT_SC_REQUESTNATHAVE				"NAT_SC_REQUESTNATHAVE"
#define M_NAT_CS_REQNATTYPE1				"NAT_CS_REQNATTYPE1"
#define M_NAT_CS_REQNATTYPE2				"NAT_CS_REQNATTYPE2"
#define M_NAT_SC_REQNATTYPE					"SC_REQNATTYPE"
#define M_NAT_CS_REQCONETYPE				"CS_REQCONETYPE"		
#define M_NAT_SC_REQCONETYPE				"SC_REQCONETYPE"
#define M_NAT_CS_COMPLETEDETECTION			"CS_COMPLETEDETECTION"

#define M_UHP_CS_CLIENTREGISTER				"UHP_CS_CLIENTREGISTER"
#define M_UHP_SC_CLIENTREGISTER				"UHP_SC_CLIENTREGISTER"
#define M_UHP_CS_UDPPORTEXCHANGE			"UHP_CS_UDPPORTEXCHANGE"				
#define M_UHP_SC_UDPPORTEXCHANGE			"UHP_SC_UDPPORTEXCHANGE"
#define M_UHP_CS_CONNECTPRIVATE				"UHP_CS_CONNECTPRIVATE"
#define M_UHP_SC_CONNECTPRIVATE				"UHP_SC_CONNECTPRIVATE"
#define M_UHP_CS_CONNECTPUBLIC				"UHP_CS_CONNECTPUBLIC"
#define M_UHP_SC_CONNECTPUBLIC				"UHP_SC_CONNECTPUBLIC"
#define M_UHP_CS_KEEPALIVEPUBLIC			"UHP_CS_KEEPALIVEPUBLIC"
#define M_UHP_CS_HOLEPUNCHINGEND			"UHP_CS_HOLEPUNCHINGEND"
#define M_UHP_SC_TARGETEXIT					"UHP_SC_TARGETEXIT"
#define M_UHP_CS_HOLEPUNCHINGSUCCESS		"UHP_CS_HOLEPUNCHINGSUCCESS"
#define M_ADDEDJIFEN						"ADDEDJIFEN"

#endif // SIP_MSG_NAME_DWORD

#endif // SIP_SYSPACKET_H
